// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'nl'

export type Locales =
	| 'en'
	| 'nl'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	GENERIC: {
		/**
		 * Geachte {title} {name} {surname}
		 * @param {string} name
		 * @param {string} surname
		 * @param {string} title
		 */
		DEAR: RequiredParams<'name' | 'surname' | 'title'>
		/**
		 * heer
		 */
		MR: string
		/**
		 * mevrouw
		 */
		MRS: string
	}
}

export type TranslationFunctions = {
	GENERIC: {
		/**
		 * Geachte {title} {name} {surname}
		 */
		DEAR: (arg: { name: string, surname: string, title: string }) => LocalizedString
		/**
		 * heer
		 */
		MR: () => LocalizedString
		/**
		 * mevrouw
		 */
		MRS: () => LocalizedString
	}
}

export type Formatters = {}
